# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'AlamoFire' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for AlamoFire
  pod 'Alamofire'
  pod 'SwiftyJSON'

  target 'AlamoFireTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'AlamoFireUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
