# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Evaluacion3' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Evaluacion3
  pod 'Alamofire', '~> 4.7.1'
  pod 'SwiftyJSON', '~> 4.1.0'

  target 'Evaluacion3Tests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'Evaluacion3UITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
